### ISSUE TITLE
Consent form no work

### ISSUE THREAD

**Issue by AndreNeves97** [admob-plus/admob-plus#179]
I'm trying to use the consent form for personalized Ads, but it's not working for me. I'd like to know if the native implementation used in this package still works, because reading this page (https://developers.google.com/admob/ump/android/quick-start) i read about use of Unified Messaging Platform SDK

When i call some methods of consent plugin, i get an promise that is never resolved or rejected.

PS: I've configured the consent form in Funding Choices Pannel

**Comment by rastafan** [comment]
This issue seems related to this other one: #144 
Try the solution described here about copying the source file manually, it should work.

About the libraries, i believe this plugin makes use of com.google.ads.consent, which seems to be deprecated.
The suggested way in the docs is in fact with the [user-messaging-platform](https://developers.google.com/admob/ump/android/quick-start).
I'm not sure what would happend using this plugin. I managed to make it work (=showing the consent windows), but i have not uploaded this version of our app yet.

**Comment by AndreNeves97** [comment]
Thanks @rastafan. Through the `adb logcat`, i saw that `Consent.java` file was not copied to correct path.
