### ISSUE TITLE
Interstitial closed event not fired in 1.0.0-alpha.13

### ISSUE THREAD

**Issue by merbin2012** [admob-plus/admob-plus#242]
**Interstitial close** event not fired in 1.0.0-alpha.13, but it is worked perfectly in 1.0.0-alpha.10, kindly find and fix the issue.

I checked with 1.0.0-alpha.11 & 1.0.0-alpha.12, these are also not working.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
_Event listeners are changed in almost every release._

**Version @1.0.0-alpha.10 has those active;**

`admob.interstitial.click`
`admob.interstitial.close`
`admob.interstitial.impression`
`admob.interstitial.load`
`admob.interstitial.open`

**Version @1.0.0-alpha.13 deleted some and introduced some;**

`admob.interstitial.dismiss`
`admob.interstitial.load`
`admob.interstitial.show`
`admob.interstitial.loadFail`
`admob.interstitial.showFail`

The documentation on the official site and / or Github are messy at best and not always up2date.

So it's best to read the source-code and check which functions are still active or deprecated.

In this case the `events` are declared here;

https://github.com/admob-plus/admob-plus/blob/b825abc303b0acd15fb8add7d0320f9d4a9ded76/packages/cordova/ts/generated.ts#L22

See my set-up for the `banner` and `interstitial` functions - they change with every release and so does my code...

![image](https://user-images.githubusercontent.com/80490580/110862420-c0cda880-82bf-11eb-8ac8-f2cd06eb76e6.png)

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
In case you are wondering what my `app__ad_event` fuction does;

_It show's basic debug-info on the canvas with some variables ( json meta-data, the caller #ID and the event #ID )._

See the screenshot - `#INT` = interstitial and `#AD` = banner.

The newest version of the plugin shows more meta-data (like the #adID), but I don't need that and it not very stable with most of the ad-listeners.

**The rest is self explanatory, I guess.**

![image](https://user-images.githubusercontent.com/80490580/110865077-5585d580-82c3-11eb-88a7-49578d5eb1de.png)

**Comment by merbin2012** [comment]
Thank you very much, but if he is changing the event name frequently, it is very difficult to manage our new apps and apps update (I mean we need to always update the ads code)

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
I am not the author of the plugin, but we should be aware it's still in bèta... or alpha even.

**So it's "normal" to make breaking changes in the code, while it's in bèta.**

The updates are quite often now and they're not always useful at this moment.

So you **don't have to update** from version `1.0@alpha.10` to `1.0@alpha.14`.

Just stick with a version that's stable enough for your purpose and keep an eye on the development of the plugin itself.

I've been spending about two weeks now getting this plugin active in my app (which is not in production at the moment).

I've found version **@0.37** quit stable, but decided to stick with **1.0@alpha.10** because it supports `AndroidX` and a newer version of the `Google Play SDK` (19.7) - like GMS (Google Mobile Services).

The event-listeners in version `1.0@alpha.10` are quite stable and both the `banner` and `interstitial` share the same namespace;

- click
- close
- impression
- load
- loadFail
- open

![image](https://user-images.githubusercontent.com/15701574/110954322-a7bd0a00-8348-11eb-851f-2cb3a2559926.png)

**Comment by ratson** [comment]
@merbin2012 Please refer to the documentation for the events, they should be stable now.
