### ISSUE TITLE
Unable to test ionic app from admob-plus example

### ISSUE THREAD

**Issue by Daniel-Richard** [admob-plus/admob-plus#27]
To replicate issue:
Extract master folder, in example > ionic-angular

npm install
ionic cordova plugin add cordova-admob-plus --variable APP_ID_ANDROID=[own_google_admob_id]
npm install --save ionic-admob
ionic serve

clicks on admob.banner.show() --> displays error below
Runtime Error
Uncaught (in promise): adView is null, cal createBannerView first

clicks on admob.interstitial.load() and admob.rewardVideo.load()
Runtime Error
Uncaught (in promise): plugin_not_installed

Currently on:
Ionic Framework: 3.9.2
Ionic App Scripts: 3.2.0
Angular Core: 5.2.11
Angular Compiler CLI: 5.2.11
Node: 8.12.0
OS Platform: Windows 10
Navigator Platform: Linux armv81
User Agent: Mozilla/5.0 (Linus: Android 8.0.0 SM-G955F

**Comment by ratson** [comment]
Would you run `npx admob-plus info --clipboard` to provide more information? Also, you may try out the latest version first to see if your problem is fixed.

**Comment by lreiner** [comment]
`Uncaught (in promise): plugin_not_installed` <- You are probably using Ionic DevApp. Admob-Plus isnt supported by Ionic DevApp. 

`Uncaught (in promise): adView is null, cal createBannerView first` <- this error probably gets thrown because Ionic DevApp cant use the plugin. The Plugin would create the banner adView. 

I already made a Request to add this plugin to the DevApp here: [Ionic Forum Request](https://forum.ionicframework.com/t/request-admob-plus-for-ionic-devapp/166166)
