### ISSUE TITLE
NSUserTrackingUsageDescription - asked even if I'm not using it

### ISSUE THREAD

**Issue by eliadAfeka** [admob-plus/admob-plus#288]
**Describe the bug**
when I upload my app to apple, it seems to use "NSUserTrackingUsageDescription". 
does it use it always ? or when I call "requestTrackingAuthorization()"? 
I need to fill privacy setting following this permission.

are you tracking the device id to set better ads ? or if set to "turned off" by default?

thanks.

**To Reproduce**
1. upload your app to store connect
2. submit your app

**Expected behavior**
submitted

**Screenshots**

**Environment**

Ionic:  Version: 6.13.1
Platform : IOS

**Comment by ratson** [comment]
It is used when calling `requestTrackingAuthorization()`

**Comment by martijnmichel** [comment]
I don't use requestTrackingAuthorization() but still get rejected because apple says the app uses NSUserTrackingUsageDescription

**Comment by OneToMany** [comment]
> I don't use requestTrackingAuthorization() but still get rejected because apple says the app uses NSUserTrackingUsageDescription

I have same problem!

**Comment by martijnmichel** [comment]
Actually, I had sent them a response with a link to this library stating that it does not use ATT as long as you don't start the request. After which they accepted my binary.

**Comment by markenapps** [comment]
This is because it is added statically in the plugin.xml. I solved the problem by removing/commenting out

`<config-file target="*-Info.plist" parent="NSUserTrackingUsageDescription">
            <string>$USAGE</string>
 </config-file>`

in the plugin.xml.

If you use a cloud-build service like I do, this is quite inconvenient. You have to do this step again for each plugin version and upload the plugin to the build service again.

It would be great if you could control whether the NSUserTrackingUsageDescription should be added via an installation parameter. In case you only use non personalized ads.
