### ISSUE TITLE
Allow Showing Multiple Banners

### ISSUE THREAD

**Issue by ratson** [admob-plus/admob-plus#3]
As @Screeze suggested in https://github.com/admob-suite/admob-suite/issues/2, it could be useful in some case.

Here are questions need to be answered before implementation,
- [ ] Is AdMob terms allow doing so?
- [ ] Any references to existing apps using this strategy?
- [ ] What the API should look like?
- [ ] Could the API be designed without requiring changing single banner use case?

**Comment by Screeze** [comment]
Not sure if you understood me right: It is not about showing multiple baners at the same time. It is about preloading multiple banners at the same time and switching between them without delay (e.g. if user switches activities fast)

Regarding 1) "is admob terms allow doing so?":
https://developers.google.com/admob/android/banner
"Set this to the unique identifier given to the ad unit in your app where ads are to be displayed. If you show banner ads in different activities, each would require an ad unit." So they actually think you need a unique Ad ID across different activities (ok in cordova we do only have one activity but it simulates multiple different screens so that should be equivalent). 
Which, turned around should implicitly would mean it must be possible we quickly switch between those. Loading them once the activity/screen is loaded seems (for me) not satisfying as time is wasted.

Regarding 3)
Provide each method like `load()` and `show()` an optional parameter which is an ad config (id + size etc). Not passing it -> Default configuration using existing API
Passing it -> Custom banner using that config. Identification via ad ID (same id must be passed to load() and show() to reference the same ad)

Or completely different/additional api:
```
const levelBanner = new BannerAd(id,cfg);
levelBanner.load().then(() => { levelBanner.show()});
```

Regarding 4)
I think with above option 1: yes. With option 2: Yes if you support 2 different options (simple use case/extended use case). Internally the simple use case could just use the extended one to make it more simple. But is this really necessary for a new library where you have the chance to improve things from ground?

**Comment by ratson** [comment]
Close as implemented in latest version.
