### ISSUE TITLE
Admob mobile SDK needs to be upgraded in order to support mediation

### ISSUE THREAD

**Issue by EYALIN** [admob-plus/admob-plus#545]
IOS will fail using mediation because for now, the Admob Mobile SDK version is 8.+
In order to support mediation it needs to be version 9.12.

@ratson can you upgrade? I will add my sponsorship too (donation).

thanks

**Comment by jmelvin** [comment]
Also seeing a problem that appears related to mediation... entry every few seconds on android...

2022-11-08 21:38:21.803 12690-12690/? I/chromium: [INFO:CONSOLE(2)] "banner loadfail  {"isTrusted":false,"cause":null,"code":3,"adId":79,"message":"Unable to instantiate mediation adapter class.","ad":{"_created":true,"_init":{},"opts":{"position":"bottom","size":"BANNER","adUnitId":"ca-app-pub-XXX/YYY","autoShow":false,"isTesting":false,"id":null},"id":79,"_loaded":true}}", source: file:///android_asset/www/js/src/main/Main.js (2)

**Comment by EYALIN** [comment]
@ratson what do you think?

**Comment by jmelvin** [comment]
My log entry above is from Android.  The Google Mobile Ads SDK version deprecation schedule is different for IOS and Android...

Android:
- https://developers.google.com/admob/android/deprecation

IOS:
- https://developers.google.com/admob/ios/deprecation

The current deprecation date for IOS v8.0 and Android v20.0 is Q1-2023.  This means the current releases are not deprecated just yet.  However, the mediation instantiation bug cited above is fixed in later releases and it would be nice to upgrade asap, sooner than a few weeks from now.

**Comment by Calsy** [comment]
@ratson account has been inactive for 3 months.

**Comment by EYALIN** [comment]
@jmelvin and @Calsy I added a PR for Admob SDK upgraded version to 9.12.0 (for IOS)
https://github.com/admob-plus/admob-plus/pull/548

hope that @ratson will insert it soon.
