### ISSUE TITLE
Missing files on cordova example provided

### ISSUE THREAD

**Issue by ManoloPololo** [admob-plus/admob-plus#644]
I have not make it to work but I was paying attention to the example provided for cordova in the folder: admob-plus-master\examples\cordova\www

There is line:
`<script type="text/javascript" src="cordova.js"></script>`
which is pointing to no valid .js file. This lead me to think that I could not make it to work even if I wanted to, because there are errors in the first place.

I just wanted to report it. That is all.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
The file cordova.js is not needed.

Every Cordova project injects this file during runtime, so what you see in that line of coffee is just a placeholder.

It has been so for at least 15 years.

When you open the browser console, you'll see a 404 message, since the file is not there yet.

You can solve this by creating an empty cordova.js file, which will be overwritten once the code is compiled.

________________________________
From: ManoloPololo ***@***.***>
Sent: Friday, January 5, 2024 12:17:32 PM
To: admob-plus/admob-plus ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [admob-plus/admob-plus] Missing files on cordova example provided (Issue #644)


I have not make it to work but I was paying attention to the example provided for cordova in the folder: admob-plus-master\examples\cordova\www

There is line:
<script type="text/javascript" src="cordova.js"></script>
which is pointing to no valid .js file. This lead me to think that I could not make it to work even if I wanted to, because there are errors in the first place.

I just wanted to report it. That is all.
