### ISSUE TITLE
Sunset Versions of play-services-ads and play-services-ads-lite Being Used

### ISSUE THREAD

**Issue by Andalusio** [admob-plus/admob-plus#674]
**Describe the bug**
com.google.android.gms:play-services-ads has added this note for play-services-ads:20.6.0:

As of June 30th 2024, this version is sunset. For more information, please visit https://developers.google.com/admob/android/deprecation.

You may not be able to release future versions of your app with this SDK version to production or open testing.

(This also applies to play-services-ads-lite.)

**To Reproduce**
1. Compile the app as a bundle.
2. Upload to Google Play Console.
3. Software's "Inbox" page on Google Play Console issues sunset versions warning for play-services-ads:20.6.0 and play-services-ads-lite:20.6.0.

**Expected behavior**
The app uploaded with no issues with Google.

**Screenshots**

**Environment**

```
(paste the output of the command here)
```

**Additional context**
It may not related, but we're all now required to target SDK 34.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
The community edition of this plugin of updated to the latest SDK version, both regular and light (GMS SDK).

________________________________
From: Andalusio ***@***.***>
Sent: Tuesday, July 16, 2024 11:48:28 PM
To: admob-plus/admob-plus ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [admob-plus/admob-plus] Sunset Versions of play-services-ads and play-services-ads-lite Being Used (Issue #674)


Describe the bug
com.google.android.gms:play-services-ads has added this note for play-services-ads:20.6.0:

As of June 30th 2024, this version is sunset. For more information, please visit https://developers.google.com/admob/android/deprecation.

You may not be able to release future versions of your app with this SDK version to production or open testing.

(This also applies to play-services-ads-lite.)

To Reproduce
Steps to reproduce the behavior:

  1.  Compile the app as a bundle.
  2.  Upload to Google Play Console.
  3.  Software's "Inbox" page on Google Play Console issues sunset versions warning for play-services-ads:20.6.0 and play-services-ads-lite:20.6.0.

Expected behavior
The app uploaded with no issues with Google.

Screenshots

Environment

(paste the output of the command here)


Additional context
It may not related, but we're all now required to target SDK 34.

**Comment by Andalusio** [comment]
Thanks for the heads-up. I'm guessing it's a forked version, or can you help provide a link to it? This issue is affecting all of my apps at the moment.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
https://github.com/EYALIN/community-admob-plus

**Comment by Andalusio** [comment]
Thanks. Will give it a shot.

**Comment by Andalusio** [comment]
Granted, version 23.0.0 leads to a compiling failure, so I used 21.0.0.
